---

- name: Ensure ssh_user .ssh directory exists
  file: dest={{ user_home }}/.ssh mode=0700 state=directory owner={{ username }} group={{ username }}

- name: Add public keys to authorized keys
  lineinfile: dest={{ user_home }}/.ssh/authorized_keys create=true line="{{ item }}" owner={{ username }} group={{ username }}
  with_items: "{{ public_keys }}"

- name: Install deploy ssh key
  copy: content="{{ ssh_deploy_private_key }}" dest={{ user_home }}/.ssh/id_rsa mode=0600 owner={{ username }} group={{ username }}
  no_log: true
