---

- name: Generate en_US.UTF-8
  locale_gen: name=en_US.UTF-8 state=present

- name: Set locale
  copy: content='LANG="en_US.UTF-8"\nLC_ALL="en_US.UTF-8"\n' dest='/etc/default/locale' mode=0644 owner=root group=root
