---

- name: Install needed packages
  apt: name={{ item }}
  with_items:
    - libpq-dev
    - autoconf
    - automake

- name: Install gunicorn
  pip: name={{ item }} executable=pip3
  with_items:
    - gunicorn
    - eventlet

- name: Install mecab
  include: install_mecab.yml

- name: Fetch project
  git: repo={{ app_repository }} accept_hostkey=yes dest={{ app_project_dir }}
  become: yes
  become_user: "{{ username }}"
  register: app_git_fetch

- name: Install project dependencies with python 2
  pip: requirements={{ app_project_dir }}/requirements.txt executable=pip2 extra_args=--user
  when: python2_installed is defined
  become: yes
  become_user: "{{ username }}"

- name: Install project dependencies with python 3
  pip: requirements={{ app_project_dir }}/requirements.txt executable=pip3 extra_args=--user
  when: python3_installed is defined
  become: yes
  become_user: "{{ username }}"

- name: Add env file
  template: src=env dest={{ app_project_dir }}/.env owner={{ username }} group={{ username }}

- name: Add google api key
  template: src=google-api.json dest={{ app_project_dir }}/google-api.json owner={{ username }} group={{ username }}

- name: Install project with python 2
  command: python setup.py install --user chdir={{ app_project_dir }}
  become: yes
  become_user: "{{ username }}"
  when: python2_installed is defined and app_git_fetch | changed

- name: Install project with python 3
  command: python setup.py install --user chdir={{ app_project_dir }}
  become: yes
  become_user: "{{ username }}"
  when: python3_installed is defined and app_git_fetch | changed
