---

- name: Install jupyter for pip2
  pip: name=jupyter executable=pip2
  when: python2_installed is defined

- name: Install jupyter for pip3
  pip: name=jupyter executable=pip3
  when: python3_installed is defined

- name: Install python2 kernel
  command: ipython2 kernel install creates=/usr/local/share/jupyter/kernels/python2
  when: python2_installed is defined

- name: Install python3 kernel
  command: ipython3 kernel install creates=/usr/local/share/jupyter/kernels/python3
  when: python3_installed is defined

- name: Add jupyter config
  template: src=jupyter.conf dest=/etc/supervisor/conf.d/jupyter.conf
  register: jupyter_config

- name: Restart supervisor
  service: name=supervisor state=restarted
  when: jupyter_config | changed

- name: Start jupyter
  supervisorctl: name=jupyter state=started
