---

- name: Fetch project
  git: repo={{ scraper_repository }} accept_hostkey=yes dest={{ scraper_project_dir }}
  become: yes
  become_user: "{{ username }}"
  register: scraper_git_fetch

- name: Install project dependencies
  pip: requirements={{ scraper_project_dir }}/requirements.txt

- name: Install project dependencies with python 3
  pip: requirements={{ scraper_project_dir }}/requirements.txt executable=pip3

- name: Add env file
  template: src=env dest={{ scraper_project_dir }}/.env owner={{ username }} group={{ username }}

- name: Install project
  command: python setup.py install --user chdir={{ scraper_project_dir }}
  become: yes
  become_user: "{{ username }}"
  when: scraper_git_fetch | changed

- name: Add supervisor fetch sources
  template: src=fetch_sources.conf dest=/etc/supervisor/conf.d/fetch_sources.conf
  register: fetch_sources_config

- name: Restart supervisor
  service: name=supervisor state=restarted
  when: fetch_sources_config | changed
